# Generated by Django 2.0.6 on 2018-06-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('many_to_many', '0007_instargramuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstargramUser',
            new_name='InstagramUser',
        ),
    ]
