# Generated by Django 2.0.6 on 2018-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0009_auto_20180618_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('b', 'Block'), ('f', 'Follow')], max_length=1),
        ),
    ]
