# Generated by Django 2.0.6 on 2018-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0017_auto_20180619_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('b', 'Block'), ('f', 'Follow')], max_length=1),
        ),
    ]
