# Generated by Django 2.0.6 on 2018-06-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0002_auto_20180619_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relateduser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='relateduser',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photopost', to='abstract_base_classes.RelatedUser'),
        ),
        migrations.AlterField(
            model_name='relateduser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textpost', to='abstract_base_classes.RelatedUser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
