# Generated by Django 2.0.6 on 2018-06-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_adminmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminManager',
        ),
        migrations.DeleteModel(
            name='PersonManager',
        ),
    ]
